// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data;

public partial class LookupProperty
{
    public int Id { get; set; }

    public long TypeId { get; set; }

    public string NameAr { get; set; }

    public string NameEn { get; set; }

    public virtual ICollection<Rooms> Rooms { get; set; } = new List<Rooms>();

    public virtual LookupRoomType Type { get; set; }
}