// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data;

public partial class Reservations
{
    public int ReservationId { get; set; }

    public string FullName { get; set; }

    public string Nationality { get; set; }

    public string NationalityId { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public bool IsAdult { get; set; }

    public DateTime CheckIn { get; set; }

    public DateTime CheckOut { get; set; }

    public bool Breakfast { get; set; }

    public bool Lunch { get; set; }

    public bool Dinner { get; set; }

    public bool ExtraBed { get; set; }

    public double Price { get; set; }

    public int RoomId { get; set; }

    public string UserId { get; set; }

    public DateTime OrderDate { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Escorts> Escorts { get; set; } = new List<Escorts>();

    public virtual Rooms Room { get; set; }

    public virtual AspNetUsers User { get; set; }
}