// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data;

public partial class Rooms
{
    public int RoomId { get; set; }

    public int Capacity { get; set; }

    public int RoomNumber { get; set; }

    public long RoomTypeId { get; set; }

    public bool Status { get; set; }

    public double PricePerNight { get; set; }

    public virtual ICollection<Reservations> Reservations { get; set; } = new List<Reservations>();

    public virtual ICollection<RoomImages> RoomImages { get; set; } = new List<RoomImages>();

    public virtual LookUpProperty RoomType { get; set; }
}