// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data;

public partial class RoomImages
{
    public int RoomImageId { get; set; }

    public string ImageUrl { get; set; }

    public int RoomId { get; set; }

    public virtual Rooms Room { get; set; }
}