// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Data;

public partial class Visitors
{
    public int VisitorId { get; set; }

    public string Ipaddress { get; set; }

    public DateTime VisitDate { get; set; }
}